# yaml-language-server: $schema=https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2024/04/bundled/config/document.vscode.json
$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json

# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

##########################################################################################################
# This configuration will install the tools necessary to get started developing in dotnet on Windows 11  #
# NOTE: Run: dsc config .\configuration.dsc.yaml                  #
##########################################################################################################

metadata:
  Microsoft.DSC:
    securityContext: elevated

resources:
  - name: assert-windows
    type: Microsoft.DSC/Assertion
    properties:
      $schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
      resources:
        - name: os
          type: Microsoft/OSInfo
          properties:
            family: Windows

  - name: Configuration Development Tools
    type: Microsoft.DSC/PowerShell
    properties:
      resources:
        - name: "7zip.7zip"
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            source: winget
            UseLatest: true
            Ensure: Present

        - name: Telerik.Fiddler.Classic
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            allowPrerelease: true
            source: winget
            UseLatest: true
            Ensure: Present

        - name: Fork.Fork
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            allowPrerelease: true
            source: winget
            UseLatest: true
            Ensure: Present

        - name: Git.Git
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            allowPrerelease: true
            source: winget
            UseLatest: true
            Ensure: Present

        - name: GitHub.cli
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            allowPrerelease: true
            source: winget
            UseLatest: true
            Ensure: Present

        - name: Google.Chrome
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            allowPrerelease: true
            source: winget
            UseLatest: true
            Ensure: Present

        - name: jqlang.jq
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            allowPrerelease: true
            source: winget
            UseLatest: true
            Ensure: Present

        - name: OpenJS.NodeJS.LTS
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            allowPrerelease: true
            source: winget
            UseLatest: true
            Ensure: Present

        - name: Notepad++.Notepad++
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            allowPrerelease: true
            source: winget
            UseLatest: true
            Ensure: Present

        - name: "9WZDNCRDMDM3"
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            allowPrerelease: true
            source: msstore
            UseLatest: true
            Ensure: Present

        - name: Microsoft.PowerShell
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            allowPrerelease: true
            source: winget
            UseLatest: true
            Ensure: Present

        - name: SlackTechnologies.Slack
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            allowPrerelease: true
            source: winget
            UseLatest: true
            Ensure: Present

        - name: TortoiseGit.TortoiseGit
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            allowPrerelease: true
            source: winget
            UseLatest: true
            Ensure: Present

        - name: Canonical.Ubuntu.2204
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            allowPrerelease: true
            source: winget
            UseLatest: true
            Ensure: Present
          dependsOn:
            - "[resourceId('Microsoft.WinGet.DSC/WinGetPackage','Wsl')]"

        - name: Microsoft.VisualStudioCode
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            source: winget
            UseLatest: true
            Ensure: Present

        - name: WinMerge.WinMerge
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            source: winget
            UseLatest: true
            Ensure: Present

        - name: "9P9TQF7MRM4R"
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            allowPrerelease: true
            source: msstore
            UseLatest: true
            Ensure: Present

    dependsOn:
      - "[resourceId('Microsoft.DSC/Assertion','assert-windows')]"

  - name: VisualStudioCode Extensions
    type: Microsoft.Windows/WindowsPowerShell
    properties:
      resources:
        - name: Script to install Visual Studio Code extensions
          type: PSDesiredStateConfiguration/Script
          properties:
            GetScript: |
              return @{ Result = 'Not implemented' }
            TestScript: |
              return $false
            SetScript: |
              # Implementation needed
    dependsOn:
      - "[resourceId('Microsoft.DSC/Assertion','assert-windows')]"
      - "[resourceId('Microsoft.WinGet.DSC/WinGetPackage','VisualStudioCode')]"

