# yaml-language-server: $schema=https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2024/04/bundled/config/document.vscode.json
$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json

# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

##########################################################################################################
# This configuration will install the tools necessary to get started developing with rest-api's          #
# NOTE: Run: dsc config .\rest-api-configuration.dsc.yaml         #
##########################################################################################################

metadata:
  Microsoft.DSC:
    securityContext: elevated

resources:
  - name: assert-windows
    type: Microsoft.DSC/Assertion
    properties:
      $schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
      resources:
        - name: os
          type: Microsoft/OSInfo
          properties:
            family: Windows

  - name: Rest-Api Development Tools
    type: Microsoft.DSC/PowerShell
    properties:
      resources:
        - name: k6.k6
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            source: winget
            UseLatest: true
            Ensure: Present

        - name: Bruno.Bruno
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            allowPrerelease: true
            source: winget
            UseLatest: true
            Ensure: Present

        - name: Postman.Postman
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            allowPrerelease: true
            source: winget
            UseLatest: true
            Ensure: Present

        - name: Insomnia.Insomnia
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            allowPrerelease: true
            source: winget
            UseLatest: true
            Ensure: Present

        - name: Stoplight.Studio
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            allowPrerelease: true
            source: winget
            UseLatest: true
            Ensure: Present

        - name: Microsoft.VisualStudioCode
          type: Microsoft.WinGet.DSC/WinGetPackage
          properties:
            allowPrerelease: true
            source: winget
            UseLatest: true
            Ensure: Present

    dependsOn:
      - "[resourceId('Microsoft.DSC/Assertion','assert-windows')]"

  - name: VisualStudioCode Extensions
    type: Microsoft.Windows/WindowsPowerShell
    properties:
      resources:
        - name: Script to install Visual Studio Code extensions
          type: PSDesiredStateConfiguration/Script
          properties:
            GetScript: |
              return @{ Result = 'Not implemented' }
            TestScript: |
              return $false
            SetScript: |
              # Implementation needed
    dependsOn:
      - "[resourceId('Microsoft.DSC/Assertion','assert-windows')]"
      - "[resourceId('Microsoft.WinGet.DSC/WinGetPackage','VisualStudioCode')]"

